name: activity13
description: "A new Flutter project."

publish_to: 'none' # Prevents this package from being published

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies with specified version numbers
  firebase_core: ^2.11.0
  firebase_auth: ^4.6.0
  firebase_auth_web: ^5.8.13  # Added for web-specific Firebase authentication
  js: ^0.6.5  # Added to handle JavaScript interop issues

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
